theme = ["awesome-identity", "plausible-hugo"]  # Add this theme to your already existing other themes
[params.plausible]
enable = true  # Whether to enable plausible tracking
domain = "mattmcnew.com"

baseURL = "https://example.com"
title = "Matthew McNew"


## Profile Configurations
[params.profile]
portrait = "/images/portrait-default.png"
firstname = "Matthew"
lastname = "McNew"
title = "Software Engineer"
bio = """
  """

[params.contacts]
email = "me@mattmcnew"
github = "matthewmcnew"
twitter = "matthewmcnew"
linkedin = "matthewmcnew"
instagram = "matthewmcnew"
dockerhub = "matthewmcnew"

## Footer Configurations
[params.footer]
copyright = ""
poweredBy = false

